config/routes.rb
Rails.application.routes.draw do
  resources :reports

  resources :staffs

  resources :loans do
    collection do
      get :amortization
    end
  end

  resources :customers

  resources :quotes do
    member do
      get 'total'
    end
  end

  resources :cars do
    member do
      get 'price'
    end
  end

  get 'sales/sales'

  root 'cars#index'

end

app/models/quote.rb
class Quote < ActiveRecord::Base

  has_one :loan
  belongs_to :car
  belongs_to :staff
  belongs_to :customer
  belongs_to :report

  after_save :marksold
  before_save :grab_price, :calc_sales_tax, :calc_total


  def marksold
    if self.sold == true
      Car.update(self.car_id, :sold => true)
    end

  end

  def grab_price
    self.price= self.car.mu_price
  end

  def calc_sales_tax
    self.sales_tax= self.price * 0.043
  end

  def calc_total
    self.total= self.price + self.sales_tax
  end


  def cuname
    "#{customer.first_name} - #{customer.last_name} - #{car.model} - #{car.color} - #{car.vin}"
  end



  def quotetype
    "#{customer.cname} - #{car.cartype}"
  end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]



   # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  def total
  logger.info "TOTAL CALLED"
  quote = Quote.find(params[:id])
  render json:quote
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:staff_id, :customer_id, :car_id, :price, :sales_tax, :total, :sold)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :staff_id %><br>
    <%= f.collection_select :staff_id, Staff.where(:position => "Sales Person"), :id, :name %>
  </div>
  <div class="field">
    <%= f.label "Customer" %><br>
    <%= f.collection_select :customer_id, Customer.all, :id, :cname %>
  </div>
  <div class="field">
    <%= f.label :car_id %><br>
    <%= f.collection_select :car_id, Car.where(:sold => false), :id, :cartype %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :sales_tax %><br>
    <%= f.text_field :sales_tax %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.text_field :total %>
  </div>
  <div class="field">
    <%= f.label :sold %><br>
    <%= f.check_box :sold %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/_quote_table.erb
<table align="center" border="1">
  <thead>
  <tr>
    <th>Staff</th>
    <th>Customer</th>
    <th>Car</th>
    <th>Price</th>
    <th>Sales tax</th>
    <th>Total</th>
    <th>Sold</th>
    <th>Actions</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody align="center">
  <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.staff.name %></td>
        <td><%= quote.customer.cname %></td>
        <td><%= quote.car.vin %></td>
        <td><%= number_to_currency(quote.price) %></td>
        <td><%= number_to_currency(quote.sales_tax) %></td>
        <td><%= number_to_currency(quote.total) %></td>
        <td><%= quote.sold %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Quotes</h1>

<p align="center"><%= link_to 'New Quote', new_quote_path %></p>

<%= render 'quote_table' %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Staff:</strong>
  <%= @quote.staff_id %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @quote.customer.cname %>
</p>

<p>
  <strong>Car:</strong>
  <%= @quote.car_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @quote.price %>
</p>

<p>
  <strong>Sales tax:</strong>
  <%= @quote.sales_tax %>
</p>

<p>
  <strong>Total:</strong>
  <%= @quote.total %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @quote.sold %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>