config/routes.rb
Rails.application.routes.draw do
  resources :reports

  resources :staffs

  resources :loans do
    collection do
      get :amortization
    end
  end

  resources :customers

  resources :quotes do
    member do
      get 'total'
    end
  end

  resources :cars do
    member do
      get 'price'
    end
  end

  get 'sales/sales'

  root 'cars#index'

end

app/models/car.rb
class Car < ActiveRecord::Base

  has_many :quotes
  before_save :calc_mu_price

  def cartype
    "#{model} - #{year} - #{color} - #{vin} "
  end

  def self.search(search)
    if search
      where('model LIKE ? OR Vin LIKE ? OR color LIKE ?',
            "%#{search}%", "%#{search}%", "%#{search}%")
    else
      self.all
    end
  end

  def calc_mu_price
      self.mu_price = self.whs_price + (self.whs_price * 0.1)
  end

  validates :model, :color, :year, :vin, :whs_price, presence: true
  validates :year, length: { is: 4}
  validates :vin, length: {is: 17}
  validates :color, format: {with: /\A[a-zA-Z]+\z/}
  validates :year, :whs_price, numericality: true
  validates :model, :color, length: {maximum: 30}

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.search(params[:search])
  end

  def price
    logger.info "PRICE CALLED"
    car = Car.find(params[:id])
    render json:car
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:model, :color, :vin, :year, :whs_price, :mu_price, :sold)
    end



end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :vin %><br>
    <%= f.text_field :vin %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :whs_price %><br>
    <%= f.text_field :whs_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Inventory</h1>


<div id="search-field-wrapper" align="center">
<%= form_tag cars_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :model => nil %>
      <%= link_to 'Cancel', cars_path %>
    </p>
<% end %>
</div>

<p align="center"> <%= link_to 'New Car', new_car_path %></p>

<table align="center" border="1">
  <thead>
    <tr>
      <th>Model</th>
      <th>Color</th>
      <th>Vin</th>
      <th>Year</th>
      <th>Wholesale price</th>
      <th>Markup price</th>
      <th>Sold</th>
      <th>Actions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody align="center">
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.model %></td>
        <td><%= car.color %></td>
        <td><%= car.vin %></td>
        <td><%= car.year %></td>
        <td><%= number_to_currency(car.whs_price) %></td>
        <td><%= number_to_currency(car.mu_price) %></td>
        <td><%= car.sold %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Color:</strong>
  <%= @car.color %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @car.vin %>
</p>

<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>

<p>
  <strong>Whs price:</strong>
  <%= @car.whs_price %>
</p>

<p>
  <strong>Mu price:</strong>
  <%= @car.mu_price %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @car.sold %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>