config/routes.rb
Rails.application.routes.draw do
  resources :reports

  resources :staffs

  resources :loans do
    collection do
      get :amortization
    end
  end

  resources :customers

  resources :quotes do
    member do
      get 'total'
    end
  end

  resources :cars do
    member do
      get 'price'
    end
  end

  get 'sales/sales'

  root 'cars#index'

end

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :quotes
  before_save :calc_tgr, :calc_st_total, :calc_net_profit



  def calc_tgr
    self.tgr = Quote.where(:sold => true).sum("total") - Car.where(:sold => true).sum("whs_price") + Loan.sum("interest_sum")
  end

  def calc_st_total
    self.sales_tax_total= Quote.where(:sold => true).sum("sales_tax")
  end

  def calc_net_profit
    self.net_profit= self.calc_tgr - self.calc_st_total + Loan.sum("interest_sum")
  end



end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @calc_tgr = @report.calc_tgr
    @calc_st_total = @report.calc_st_total
    @calc_net_profit = @report.calc_net_profit
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:tgr, :net_profit, :sales_tax_total, :date)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




  <div class="field">
    <%= f.label :tgr, "Total Gross Revenue:" %><br>
    <%= number_to_currency(@report.calc_tgr) %>
    <%= f.text_field :tgr, :class => "hidden"%>
  </div>
  <div class="field">
    <%= f.label :net_profit, "Net Profit:" %><br>
    <%= number_to_currency(@report.calc_net_profit) %>
    <%= f.text_field :net_profit, :class => "hidden" %>
  </div>
  <div class="field">
    <%= f.label :sales_tax_total, "Sales Tax Total:" %><br>
    <%= number_to_currency(@report.calc_st_total) %>
    <%= f.text_field :sales_tax_total, :class => "hidden" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Reports</h1>

<table align="center" border="1">
  <thead>
    <tr>
      <th>Total Gross Revenue</th>
      <th>Net Profit</th>
      <th>Sales Tax Total</th>
      <th>Date</th>
      <th>Actions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <p align="center"><%= link_to 'New Report', new_report_path %></p>

  <tbody align="center">
    <% @reports.each do |report| %>
      <tr>
        <td><%= number_to_currency(report.tgr) %></td>
        <td><%= number_to_currency(report.net_profit) %></td>
        <td><%= number_to_currency(report.sales_tax_total) %></td>
        <td><%= report.created_at.strftime("%x") %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tgr:</strong>
  <%= number_to_currency(@calc_tgr) %>
</p>

<p>
  <strong>Net profit:</strong>
  <%= number_to_currency(@calc_net_profit) %>
</p>

<p>
  <strong>Sales tax total:</strong>
  <%= number_to_currency(@calc_st_total) %>
</p>

<p>
  <strong>Date:</strong>
  <%= @report.created_at.strftime("%x") %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>